### PR TITLE
Fix issue with messages on myposts page being unreactive

### LINKED ISSUE #39: After deleting the last WANTED in the list, the button to ask for stuff won't become visible
After deleting the last WANTED in the list, the button to ask for stuff won't become visible:

Screenshot_20231005_202638

After refreshing the page it's there.

Screenshot_20231005_202646

### PR DESCRIPTION
**Pull request by misterpekert**
- use value from store instead of response from API
- correctly update store when item is processed (withdraw/taken)

closes #39

### CODE REVIEW

File: stores/message.js [hunk 1]
```diff
@@ -173,6 +174,16 @@ export const useMessageStore = defineStore({
...
+      const findByIdAndUpdate = (messages) => {
+        messages.forEach((message) => {
+          const i = this.byUserList[userid].findIndex(curMessage => curMessage.id === message.id)
+          if (i !== -1) {
+            this.byUserList[userid][i] = message
+          } else {
+            this.byUserList[userid].push(message)
+          }
+        })
+      }
```
Comment (edwh) [inline stores/message.js:186]: I don't think this has quite the same effect as the old code.  It's possible that a message has been deleted on the server side (by a moderator).  I think this new code would leave that deleted message in store.

I always have to think hard about replacing the whole array, and whether it works reactively.  But could we use `Vue.set(this.byUserList, userid, messages)`?  That would be neater than a loop.

**Review by edwh — CHANGES_REQUESTED** [review]

File: stores/message.js (hunk 1 above)
Comment (misterpekert) [reply stores/message.js:186]: There is no more Vue.set in vue 3 :)

So, my idea was to update those messages we have already in store when we receive new messages from the API. And, if we have 50 messages loaded and then the response comes containing 10 items, we would update data for those 10 items and leave the other 40 intact. I was thinking that the response might be paginated, if not and we always get all user messages, we can surely just replace what we have in the store.

Comment (misterpekert) [reply stores/message.js:186]: I've pushed the fix which updates per item from response only for `active: true`. As I understand, when `active: false` we always get all the messages user have

Comment (edwh) [reply stores/message.js:186]: The `active` parameter controls whether the API returns messages which have not yet been TAKEN/RECEIVED (active = true) or all messages (active = false).  It's not relevant here, so you should revert that change.

The response isn't paginated. So yes, you can replace all the ones you currently have, but you also need to remove the ones that have no longer been returned from the server.  This would be true even if the response was paginated.

Suppose you initially have messages A, B, C in store on the client.  The message B is deleted on the server while the client still has the page open.  The user fetches messages again, and will receive messages A and C.  The code will loop through and update messages A and C, but message B will remain in the store.  That's the bug.

If this still isn't clear, then let's have a Slack call.

File: stores/message.js [hunk 2]
```diff
@@ -215,14 +234,36 @@ export const useMessageStore = defineStore({
       await api(this.config).message.view(id)
     },
     async update(params) {
+      const authStore = useAuthStore()
+      const userUid = authStore.user?.id
+      const removeFromUserList = (id) => {
+        const index = this.byUserList[userUid].findIndex(curMessage => curMessage.id === id)
+        if (index !== -1) {
+          this.byUserList[userUid] = [
```
Comment (misterpekert) [inline stores/message.js:242]: Rewrite with `filter()`

File: stores/message.js [hunk 3]
```diff
@@ -274,6 +306,21 @@ export const useMessageStore = defineStore({
     async intend(id, outcome) {
       await api(this.config).message.intend(id, outcome)
     },
+    async fetchActivePostCount() {
+      const authStore = useAuthStore()
+      const userUid = authStore.user?.id
+
+      return api(this.config).message.fetchByUser(userUid, false)
```
Comment (edwh) [inline stores/message.js:313]: I prefer to use `await` rather than `then`, please

File: stores/message.js [hunk 4]
```diff
@@ -189,7 +201,11 @@ export const useMessageStore = defineStore({
           }
         }
 
-        this.byUserList[userid] = messages
+        if (Array.isArray(this.byUserList[userid]) && active) {
```
Comment (edwh) [inline stores/message.js:204]: I don't understand why we have the `&& active` check here and below.  Can you explain?

File: stores/message.js (hunk 1 above)
Comment (edwh) [reply stores/message.js:187]: @misterpekert I think `findByIdAndUpdate` still has this issue.  If a message is no longer returned from the server, it will be left in the store.

File: stores/message.js (hunk 4 above)
Comment (misterpekert) [reply stores/message.js:204]: If active is true, we might not get all the posts of the user, so in order not to lose old posts, we will use that response and update items we already have in store

File: stores/message.js (hunk 1 above)
Comment (misterpekert) [reply stores/message.js:187]: Yeah, you’re right. I think we need to always fetch all posts in this case with `active: false`, otherwsie we might end up with missmatch between client and server. I’ll update the PR

**Comment by edwh** [comment]
@misterpekert This PR is getting complex.  I think it might be better to split it.

The first issue is that My Posts is not using computed properties to get the messages from the store, and therefore is not reactive.  

The second issue is about updating the store correctly.  I'm not what the actual problem is here, and therefore I'm not sure your changes are heading in the right direction.

Would it help to split this and release the first part?

File: stores/message.js (hunk 3 above)
Comment (edwh) [inline stores/message.js:313]: The active post count includes only active messages.  So when you are fetching the messages for the count, you should pass `true`.

**Comment by edwh** [comment]
> I think it might be better to split it.

Ignore that.  Having looked at it a bit more I can't see how it could be split.

File: stores/message.js (hunk 4 above)
Comment (edwh) [reply stores/message.js:204]: If a post has been deleted on the server, we **want** to remove it on the client.

Now that you have moved the active count check into a separate function which doesn't affect the state in the store, can we just revert to setting `this.byUserList[userid] = messages`?

**Review by edwh — APPROVED** [review]
